version: '1.0'
stages:
  - checkout
  - package
  - test  
steps:
  main_clone:
    title: Cloning main repository...
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
    stage: checkout
  
  Initialize:
    type: parallel
    stage: initialize
    title: Clone github repositories
    steps:
      Init_pipeline:
        stage: Initialize
        title: Initialize pipeline
        type: emburse/initialize-pipeline

    Clone_repo:
      stage: Initialize
      title: Cloning repository ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
      type: git-clone
      repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
      revision: ${{CF_BRANCH}}
      git: Chrome-River

  MyAppDockerImage:
    title: Building Docker Image
    type: build
    stage: package
    image_name: osergiyuk/python-sample-app
    working_directory: ./
    tag: v1.0.1
    dockerfile: Dockerfile
    disable_push: true
  MyUnitTests:
    title: Running Unit tests
    image: '${{MyAppDockerImage}}'
    stage: test 
    commands: 
      - pip install pytest
      - pytest
  Deployment:
